name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9] # Updated to valid versions

    steps:
    - name: Check out code
      uses: actions/checkout@v2 # Latest version

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2 # Latest version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest --disable-warnings
